version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  hello:
    executor: my-executor
    steps:
      - run: echo "Hello, "
  
  world:
    executor: my-executor
    steps:
      - run: echo "World!"

workflows:
  hello_world:
    jobs:
      - hello
      - world:
          requires:
            - hello
  