version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace/build
      - run: npm i
      - run: npm run build
      - run: cp build/* /tmp/workspace/build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build

  test:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  # create_infrastructure:
  #   docker:
  #     - image: cimg/aws:2022.11
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create CloudFormation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file infra.yaml \
  #             --stack-name infraStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
  
  # configure_infrastructure:
  #   docker:
  #     - image: python:3.7-alpine3.11
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints: ["22:55:20:93:36:22:44:2c:ba:37:57:bb:32:70:57:e3"]
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           apk add --update ansible
  #     - run: 
  #         name: Configure Server
  #         command: | 
  #           ansible-playbook -i inventory.txt main.yml

workflows:
  infra_workflow:
    jobs:
      - build
      - test





# version: 2.1
# executors:
#   node-executor:
#     docker:
#       - image: circleci/node:16.10.0
# jobs:
#   build:
#     executor: node-executor
#     steps:
#       - checkout
#       - run: npm i
#       - run: mkdir -p /tmp/workspace /tmp/artifacts/build
#       - run: npm run build
#       - run: cp build/* /tmp/artifacts/build
#       - run: mv build/main.bundle.min.js /tmp/workspace/
#       - persist_to_workspace:
#           root: /tmp/workspace
#           paths:
#             - main.bundle.min.js
#       - save_cache:
#           key: "npm-packages"
#           paths:
#             - /node_modules
#       - store_artifacts:
#           path: /tmp/artifacts/build
#   test:
#     executor: node-executor
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - "npm-packages"
#       - run: npm i
#       - run: npm run test
#   analyze:
#     executor: node-executor
#     steps:
#       - checkout
#       - run: npm i
#       - run: npm run analyze
#       - attach_workspace:
#           at: /tmp/workspace
#       - run: cat /tmp/workspace/main.bundle.min.js
# workflows:
#   build_test_analyze:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - analyze:
#           requires:
#             - test
