version: 2.1

# commands:
#   print_greeting:
#     parameters:
#       greeting:
#         type: string
#         default: Hello,
#       person_to_greet:
#         type: string
#         default: World
#     steps:
#       - run: echo <<parameters.greeting>> <<parameters.person_to_greet>>

executors:
  node-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    executer: node-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      # - save_cache:
      #     key: "npm-packages"
      #     paths:
      #         - /node_modules

  test:
    executor: node-executor
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    executor: node-executor
    steps:
      - run: npm run analyze
  
workflows:
  build_test_analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test