version: 2.1

# commands:
#   print_greeting:
#     parameters:
#       greeting:
#         type: string
#         default: Hello,
#       person_to_greet:
#         type: string
#         default: World
#     steps:
#       - run: echo <<parameters.greeting>> <<parameters.person_to_greet>>

executors:
  node-executor:
    docker:
      - image: circleci/node:16.10.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm i
      - run: mkdir -p /tmp/workspace/artifact
      - run: touch artifact.js
      - run: npm run build && cp build/main.bundle.min.js artifact.js
      - persist_to_workspace:
          root: tmp/workspace/artifact
          paths:
            - artifact.js
      - save_cache:
          key: "npm-packages"
          paths:
            - /node_modules

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    executor: node-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run analyze
      - attach_workspace:
          at: /tmp/workspace/artifact
      - run: cat /tmp/workspace/artifact/artifact.js
  
workflows:
  build_test_analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test