--- 
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "remove deps that are no longer needed"
  become: true
  apt: 
    autoremove: yes

- name: "install nginx"
  become: true
  apt:
    name: ["nginx"]
    state: latest
    update_cache: yes

- name: "copy index html page"
  become: true
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes

- name: "copy index JS"
  become: true
  copy:
    src: main.bundle.min.js
    dest: /var/www/html/main.bundle.min.js
    backup: yes